name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          
      - name: run python
        run: |
          python runpython.py
          echo "This is from Github Action!" >> README.md
          ls -l
      - name: push file
        run: | 
          git add *
          git commit -m "new change"
          git push origin master
